using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Daitoshi;

namespace Daitoshi
{
    public class Industry : Building
    {   
        public IList<Employee> employees;
        public int employeeCapacity;
        public float fixedCost;
        public Industry()
        {

        }
        public float processWork(Employee employee){
            //Resources generated by employee = Employee Work Quality
            //Revenue = Number of resource made + Building Wealth
            return 0.0f;
        }
    }
}
