using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Daitoshi;

namespace Daitoshi
{
    public class Industry : Business
    {   
        public int resources;
        public Industry()
        {

        }
        public float processWork(Employee employee){
            //Resources generated by employee = Employee Work Quality
            //Revenue = Number of resource made + Building Wealth
            return 0.0f;
        }
    }
}
